/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.edu.seu.iws.gspan;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Limited
 */
public class ChildResultFrame extends javax.swing.JFrame {

    private JFileChooser openFile;
    private File file;
    private ArrayList<String> relationships;
    private ArrayList<ChildGraph> Graphs;
    private ArrayList<String> names;
    private ArrayList<String> pictures;

    /**
     * Creates new form ChildResultFrame
     */
    public ChildResultFrame() {
        initComponents();

        LoadResult();
    }

    ChildResultFrame(File writefile) {
        initComponents();

        openFile = new JFileChooser();
        openFile.setSelectedFile(writefile);
        file = writefile;
        relationships = new ArrayList<String>();
        Graphs = new ArrayList<ChildGraph>();
        names = new ArrayList<String>();
        pictures = new ArrayList<String>();
    }

    private void LoadResult() {

        /// Show graphs
        ArrayList<String> result = new ArrayList<String>();

        List<Integer> diem;
        diem = new ArrayList<Integer>();
        Point[] luudiem;
        luudiem = new Point[50];
        for (int i = 0; i < luudiem.length; i++) {
            luudiem[i] = new Point(0, 0);
        }

        Graphics g;
        g = jPanel1.getGraphics();
        g.clearRect(0, 0, jPanel1.getWidth(), jPanel1.getWidth());
        MyGraphics g2d = new MyGraphics(g);

        if (Graphs.size() >= 1) {
            for (ChildGraph Graph : Graphs) {
                for (String Point : Graph.Points) {
                    result.clear();
                    String[] splitread = Point.split(" ");
                    for (String aa : splitread) {
                        result.add(aa);
                    }

                    int id = Integer.parseInt(result.get(1));
                    int label = Integer.parseInt(result.get(2));
                    diem.add(id);

                    g2d.DrawPoint(luudiem, id, names.get(id), pictures.get(id));
                }

                for (String Vector : Graph.Vectors) {
                    result.clear();
                    String[] splitread = Vector.split(" ");
                    for (String aa : splitread) {
                        result.add(aa);
                    }

                    int from = Integer.parseInt(result.get(1));
                    int to = Integer.parseInt(result.get(2));
                    int elabel = Integer.parseInt(result.get(3));
                    String strlabel = relationships.get(elabel - 1);
                    g2d.VeCanh(luudiem[from], luudiem[to], strlabel);
                }
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnSingle = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kết quả");
        setMaximumSize(null);
        setMinimumSize(null);
        setSize(new java.awt.Dimension(680, 489));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Reload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        btnSingle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSingle.setText("Open single graph");
        btnSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnSingle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnSingle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (openFile.getSelectedFile() != null) {

            List<Integer> diem;
            diem = new ArrayList<Integer>();

            File readfile = new File(openFile.getSelectedFile().getPath());
            Point[] luudiem;
            luudiem = new Point[50];
            for (int i = 0; i < luudiem.length; i++) {
                luudiem[i] = new Point(0, 0);
            }
            Graphics g;

            g = jPanel1.getGraphics();

            MyGraphics g2d = new MyGraphics(g);

            try {
                FileReader reader = new FileReader(readfile);
                BufferedReader buffer = new BufferedReader(reader);
                ArrayList<String> result = new ArrayList<String>();
                ArrayList<String> lines = new ArrayList<String>();
                String readline;

                while ((readline = buffer.readLine()) != null) {
                    lines.add(readline);
                }

                /// Read Relationships
                int index = 0;
                while (!("rrr".equals(lines.get(index)))) {
                    relationships.add(lines.get(index));
                    index++;
                }
                index++;

                /// Read Names
                while (!("nnn".equals(lines.get(index)))) {
                    names.add(lines.get(index));
                    index++;
                }

                index++;
                
                /// Read Pictures' Links
                while (!("ppp".equals(lines.get(index)))) {
                    pictures.add(lines.get(index));
                    index++;
                }
                index++;
                
                /// Save to Graphs
                ///index = 0;

                while (index < lines.size()) {
                    String line = lines.get(index);

                    if (line.charAt(0) != 't') {

                    } else /// line[0] == 't'
                    {
                        ChildGraph childGraph = new ChildGraph();
                        childGraph.t = line;
                        index++;

                        while ((index < lines.size()) && (lines.get(index).charAt(0) != 't')) {
                            if (lines.get(index).charAt(0) == 'v') {
                                childGraph.Points.add(lines.get(index));
                            }

                            if (lines.get(index).charAt(0) == 'e') {
                                childGraph.Vectors.add(lines.get(index));
                            }

                            index++;
                        }

                        if (!Graphs.contains(childGraph)) {
                            Graphs.add(childGraph);
                        }

                        index--;
                    }

                    index++;
                }

                /// Show graphs
                if (Graphs.size() >= 1) {
                    for (ChildGraph Graph : Graphs) {
                        for (String Point : Graph.Points) {
                            result.clear();
                            String[] splitread = Point.split(" ");
                            for (String aa : splitread) {
                                result.add(aa);
                            }

                            int id = Integer.parseInt(result.get(1));
                            int label = Integer.parseInt(result.get(2));
                            diem.add(id);
                            
                            g2d.DrawPoint(luudiem, id, names.get(id), pictures.get(id));
                        }

                        for (String Vector : Graph.Vectors) {
                            result.clear();
                            String[] splitread = Vector.split(" ");
                            for (String aa : splitread) {
                                result.add(aa);
                            }

                            int from = Integer.parseInt(result.get(1));
                            int to = Integer.parseInt(result.get(2));
                            int elabel = Integer.parseInt(result.get(3));
                            String strlabel = relationships.get(elabel - 1);
                            g2d.VeCanh(luudiem[from], luudiem[to], strlabel);

                        }
                    }

                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoadResult();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingleActionPerformed
        // TODO add your handling code here:
        SingleGraphFrame frmSingleGraph = new SingleGraphFrame(file);
        frmSingleGraph.show();
    }//GEN-LAST:event_btnSingleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChildResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChildResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChildResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChildResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChildResultFrame().setVisible(true);
                ///LoadResult();
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSingle;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
